import { $, state } from './state.js';
import { t as trans } from './i18n.js';
import { genId, esc, fmtTime24 } from './utils.js';
import * as api from './api.js';
import * as render from './render.js';
import { getDocs, getBudget, getItin, getPacking, getMembers } from './data.js';

export function bindTabBar() {
  const bar = $('tab-bar'); if (!bar) return;
  bar.onclick = e => { const btn = e.target.closest('.tab-btn'); if (!btn) return; bar.querySelectorAll('.tab-btn').forEach(b => { b.classList.remove('active'); b.classList.add('text-gray-400'); b.setAttribute('aria-selected', 'false'); }); btn.classList.add('active'); btn.classList.remove('text-gray-400'); btn.setAttribute('aria-selected', 'true'); document.querySelectorAll('.tab-content').forEach(c => c.classList.add('hidden')); const id = 'tab-' + btn.dataset.tab; const tabEl = document.getElementById(id); if (tabEl) tabEl.classList.remove('hidden'); };
}

export function bindBookshelf(shelfId) {
  const el = $(shelfId); if (!el) return;
  el.addEventListener('click', e => { const mb = e.target.closest('.menu-btn'); if (mb) { e.stopPropagation(); showContextMenu(e, mb.dataset.id); return; } const card = e.target.closest('[data-id]'); if (card) openTrip(card.dataset.id); });
}

export function openTrip(id) {
  state.currentTrip = state.trips.find(x => x.__backendId === id); if (!state.currentTrip) return;
  const members = getMembers(state.currentTrip); state.packingMember = members[0] || null; state.packingStage = 'outbound'; updateStageUI();
  $('home-view').classList.add('hidden'); $('detail-view').classList.remove('hidden');
  render.renderTabBar(); bindTabBar();
  document.querySelectorAll('.tab-content').forEach((c, i) => c.classList.toggle('hidden', i !== 0));
  render.renderDetail(); if (window.lucide) window.lucide.createIcons();
}

export function updateStageUI() { const o = $('btn-stage-outbound'), r = $('btn-stage-return'); if (!o || !r) return; if (state.packingStage === 'outbound') { o.className = "px-4 py-1.5 rounded-full text-xs font-medium transition-all bg-emerald-600 text-white"; r.className = "px-4 py-1.5 rounded-full text-xs font-medium transition-all text-gray-500 hover:text-emerald-600"; } else { r.className = "px-4 py-1.5 rounded-full text-xs font-medium transition-all bg-emerald-600 text-white"; o.className = "px-4 py-1.5 rounded-full text-xs font-medium transition-all text-gray-500 hover:text-emerald-600"; } }

export function handleItemAction(e, tabType) {
  const eb = e.target.closest('.act-edit'); if (eb) { openItemModal(tabType, +eb.dataset.idx); return true; }
  const db = e.target.closest('.act-dup'); if (db) { dupItem(tabType, +db.dataset.idx); return true; }
  const dl = e.target.closest('.act-del'); if (dl) { delItem(tabType, +dl.dataset.idx); return true; }
  return false;
}

export async function delItem(type, idx) {
  const trip = state.currentTrip; if (!trip) return; if (type === 'documents') { const a = getDocs(trip); a.splice(idx, 1); trip.documents = JSON.stringify(a); } else if (type === 'budget') { const a = getBudget(trip); a.splice(idx, 1); trip.budget = JSON.stringify(a); } else if (type === 'itinerary') { const a = getItin(trip); a.splice(idx, 1); trip.itinerary = JSON.stringify(a); } render.renderDetail(); await api.saveTrip(trip);
}
export async function dupItem(type, idx) {
  const sfx = state.lang === 'vi' ? ' (bản sao)' : ' (copy)'; const trip = state.currentTrip; if (!trip) return; if (type === 'documents') { const a = getDocs(trip); const it = { ...a[idx], id: genId(), checked: false, status: 'draft' }; it.name = (it.name || '') + sfx; a.splice(idx + 1, 0, it); trip.documents = JSON.stringify(a); } else if (type === 'budget') { const a = getBudget(trip); const it = { ...a[idx], id: genId(), paid: false, status: 'unpaid' }; it.name = (it.name || '') + sfx; a.splice(idx + 1, 0, it); trip.budget = JSON.stringify(a); } else if (type === 'itinerary') { const a = getItin(trip); const it = { ...a[idx], id: genId(), checked: false, status: 'planned' }; it.title = (it.title || '') + sfx; a.splice(idx + 1, 0, it); trip.itinerary = JSON.stringify(a); } render.renderDetail(); await api.saveTrip(trip);
}
export async function delPackItem(g, i) { const trip = state.currentTrip; if (!trip) return; const pk = getPacking(trip); const md = pk[state.packingMember] || { outbound: {}, return: {} }; const sd = md[state.packingStage] || {}; if (sd[g]) { sd[g].splice(i, 1); if (!sd[g].length) delete sd[g]; } md[state.packingStage] = sd; pk[state.packingMember] = md; trip.packing = JSON.stringify(pk); render.renderPacking(); await api.saveTrip(trip); }
export async function dupPackItem(g, i) { const sfx = state.lang === 'vi' ? ' (bản sao)' : ' (copy)'; const trip = state.currentTrip; if (!trip) return; const pk = getPacking(trip); const md = pk[state.packingMember] || { outbound: {}, return: {} }; const sd = md[state.packingStage] || {}; if (sd[g] && sd[g][i]) { const it = { ...sd[g][i], id: genId(), checked: false, status: 'not_started' }; it.item = (it.item || '') + sfx; sd[g].splice(i + 1, 0, it); } md[state.packingStage] = sd; pk[state.packingMember] = md; trip.packing = JSON.stringify(pk); render.renderPacking(); await api.saveTrip(trip); }

export function promptMember(existing) {
  const ov = document.createElement('div'); ov.className = 'fixed inset-0 z-[60] modal-overlay flex items-center justify-center p-4'; ov.innerHTML = `<div class="bg-white rounded-2xl shadow-xl w-full max-w-xs p-5 anim-slide-up"><label class="text-sm font-medium text-gray-600 block mb-2" for="vp-member-inp">${trans('member_name')}</label><input type="text" id="vp-member-inp" value="${esc(existing || '')}" class="w-full px-3 py-2 border border-pink-100 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-emerald-200 mb-3"><div class="flex gap-2"><button type="button" class="vp-ok flex-1 py-2 rounded-full bg-emerald-600 text-white text-sm font-medium">${trans('modal_btn_save')}</button><button type="button" class="vp-cancel flex-1 py-2 rounded-full bg-gray-100 text-gray-600 text-sm font-medium">${trans('modal_btn_cancel')}</button></div></div>`;
  document.body.appendChild(ov); const inp = ov.querySelector('#vp-member-inp'); inp.focus(); inp.select();
  return new Promise(res => { function done(v) { res(v); ov.remove(); } ov.querySelector('.vp-ok').onclick = () => done(inp.value.trim()); ov.querySelector('.vp-cancel').onclick = () => done(''); inp.onkeydown = e => { if (e.key === 'Enter') { e.preventDefault(); done(inp.value.trim()); } if (e.key === 'Escape') done(''); }; });
}

export function showContextMenu(event, id) {
  event.stopPropagation(); event.preventDefault(); const menu = $('context-menu'); if (!menu) return; if (state.contextTripId === id && !menu.classList.contains('hidden')) { menu.classList.add('hidden'); state.contextTripId = null; return; } state.contextTripId = id; const mb = event.currentTarget || event.target.closest('.menu-btn'); const r = mb.getBoundingClientRect(); menu.style.top = (r.bottom + 4) + 'px'; menu.style.left = Math.min(r.left, window.innerWidth - 200) + 'px'; menu.classList.remove('hidden'); const trip = state.trips.find(x => x.__backendId === id); const archiveTextEl = document.getElementById('archive-menu-text'); if (archiveTextEl) archiveTextEl.textContent = trip && trip.status === 'archived' ? trans('menu_reopen') : trans('menu_archive'); }

export function openTripModal(title, name, dates) {
  state.editingTripId = null; state.duplicateSourceTrip = null; const err = $('trip-name-error'); if (err) { err.textContent = ''; err.classList.add('hidden'); }
  const mt = $('modal-title'); if (mt) mt.textContent = title; $('trip-name-input').value = name || ''; let start = '', end = ''; if (dates) { const parts = dates.split(/ – | - |,/); start = (parts[0] || '').trim(); end = (parts[1] || '').trim(); [start, end] = [start, end].map(s => { if (s && !/^\d{4}-\d{2}-\d{2}$/.test(s)) { const d = new Date(s); return isNaN(d) ? '' : d.toISOString().split('T')[0]; } return s; }); } $('trip-start-input').value = start; $('trip-end-input').value = end; const overlay = $('modal-overlay'); if (overlay) overlay.classList.remove('hidden'); $('trip-name-input').focus(); }

export function closeTripModal() { const overlay = $('modal-overlay'); if (overlay) overlay.classList.add('hidden'); state.editingTripId = null; state.duplicateSourceTrip = null; }

export function openItemModal(tabType, idx) {
  state.itemModal = { tabType: tabType, idx: idx, group: null };
  const titleMap = { documents: trans('add_doc'), budget: trans('add_budget'), itinerary: trans('add_itin') };
  const titleEl = $('item-modal-title'); if (titleEl) titleEl.textContent = titleMap[tabType] || trans('btn_add');
  const form = $('item-form'); if (!form) return; form.innerHTML = ''; const trip = state.currentTrip; const isNew = idx === null || idx === undefined;
  if (tabType === 'documents') { const arr = getDocs(trip); const it = isNew ? { name: '', pic: '', cost: '', start_date: '', end_date: '', notes: '', status: 'draft' } : arr[idx]; form.innerHTML = `<div><label class="text-xs font-medium text-gray-600">${trans('item_name')}</label><input name="name" value="${esc(it.name||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div class="grid grid-cols-2 gap-3"><div><label class="text-xs font-medium text-gray-600">${trans('item_pic')}</label><input name="pic" value="${esc(it.pic||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div><label class="text-xs font-medium text-gray-600">${trans('item_cost')}</label><input name="cost" value="${esc(it.cost||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div></div><div><label class="text-xs font-medium text-gray-600">${trans('item_notes')}</label><textarea name="notes" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1">${esc(it.notes||'')}</textarea></div>`; }
  else if (tabType === 'budget') { const arr = getBudget(trip); const it = isNew ? { name: '', cost: '', currency: 'VND', note: '', status: 'unpaid' } : arr[idx]; form.innerHTML = `<div><label class="text-xs font-medium text-gray-600">${trans('item_name')}</label><input name="name" value="${esc(it.name||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div class="grid grid-cols-2 gap-3"><div><label class="text-xs font-medium text-gray-600">${trans('item_cost')}</label><input name="cost" value="${esc(it.cost||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div><label class="text-xs font-medium text-gray-600">${trans('budget_col_currency')}</label><input name="currency" value="${esc(it.currency||'VND')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div></div><div><label class="text-xs font-medium text-gray-600">${trans('item_notes')}</label><textarea name="note" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1">${esc(it.note||'')}</textarea></div>`; }
  else if (tabType === 'itinerary') { const arr = getItin(trip); const it = isNew ? { date: '', time: '', title: '', location: '', notes: '', status: 'planned' } : arr[idx]; form.innerHTML = `<div class="grid grid-cols-2 gap-3"><div><label class="text-xs font-medium text-gray-600">${trans('item_date')}</label><input name="date" type="date" value="${esc(it.date||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div><label class="text-xs font-medium text-gray-600">${trans('item_time')}</label><input name="time" value="${esc(it.time||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div></div><div><label class="text-xs font-medium text-gray-600">${trans('item_title')}</label><input name="title" value="${esc(it.title||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div><label class="text-xs font-medium text-gray-600">${trans('item_location')}</label><input name="location" value="${esc(it.location||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div><label class="text-xs font-medium text-gray-600">${trans('item_notes')}</label><textarea name="notes" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1">${esc(it.notes||'')}</textarea></div>`; }
  state.itemModal = { tabType: tabType, idx: idx, group: null };
  const overlay = $('item-modal-overlay'); if (overlay) overlay.classList.remove('hidden'); const inputs = overlay.querySelectorAll('input,textarea'); inputs.forEach(i => i.addEventListener('keydown', e => { if (e.key === 'Enter' && i.tagName !== 'TEXTAREA') { e.preventDefault(); const btn = $('item-save-btn'); if (btn) btn.click(); } }));
}

export function openPackingModal(group, idx) {
  state.itemModal = { tabType: 'packing', idx: idx, group: group };
  const titleEl = $('item-modal-title'); if (titleEl) titleEl.textContent = state.itemModal.idx === null ? trans('add_packing') : trans('edit_packing');
  const form = $('item-form'); if (!form) return; form.innerHTML = '';
  const pk = getPacking(state.currentTrip); const md = pk[state.packingMember] || { outbound: {}, return: {} }; const sd = md[state.packingStage] || {}; const it = (group && sd[group] && sd[group][idx]) || { item: '', note: '', status: 'not_started' };
  form.innerHTML = `<div><label class="text-xs font-medium text-gray-600">${trans('item_item')}</label><input name="item" value="${esc(it.item||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div><label class="text-xs font-medium text-gray-600">${trans('item_notes')}</label><input name="note" value="${esc(it.note||'')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div><div><label class="text-xs font-medium text-gray-600">${trans('item_category')}</label><input name="category" value="${esc(group||'Other')}" class="w-full px-3 py-2 rounded-xl border border-pink-100 mt-1"></div>`;
  const overlay = $('item-modal-overlay'); if (overlay) overlay.classList.remove('hidden');
}

export function bindEvents() {
  const prev = $('carousel-prev'); const next = $('carousel-next'); if (prev) prev.onclick = () => $('bookshelf').scrollBy({ left: -320, behavior: 'smooth' }); if (next) next.onclick = () => $('bookshelf').scrollBy({ left: 320, behavior: 'smooth' });
  bindBookshelf('bookshelf'); bindBookshelf('archived-bookshelf'); const back = $('back-btn'); if (back) back.onclick = () => { $('detail-view').classList.add('hidden'); $('home-view').classList.remove('hidden'); state.currentTrip = null; };
  const o = $('btn-stage-outbound'); const r = $('btn-stage-return'); if (o) o.onclick = () => { state.packingStage = 'outbound'; updateStageUI(); render.renderPacking(); }; if (r) r.onclick = () => { state.packingStage = 'return'; updateStageUI(); render.renderPacking(); };

  const copyBtn = $('btn-copy-outbound'); if (copyBtn) copyBtn.onclick = async () => { if (!state.currentTrip || !state.packingMember) return; const pk = getPacking(state.currentTrip); const md = pk[state.packingMember] || { outbound: {}, return: {} }; const rd = {}; Object.entries(md.outbound || {}).forEach(([g, items]) => { if (Array.isArray(items)) rd[g] = items.map(it => ({ item: it.item || '', note: it.note || '', status: 'not_started', checked: false, id: genId() })); }); md.return = rd; pk[state.packingMember] = md; state.currentTrip.packing = JSON.stringify(pk); render.renderPacking(); await api.saveTrip(state.currentTrip); };

  const membersContainer = $('members-container'); if (membersContainer) membersContainer.addEventListener('click', async e => { const rm = e.target.closest('.member-remove'); if (rm) { e.stopPropagation(); const chip = rm.closest('.member-chip'); const name = chip.dataset.member; const members = getMembers(state.currentTrip); if (members.length <= 1) return; members.splice(members.indexOf(name), 1); state.currentTrip.members = JSON.stringify(members); const pk = getPacking(state.currentTrip); delete pk[name]; state.currentTrip.packing = JSON.stringify(pk); if (state.packingMember === name) state.packingMember = members[0] || null; render.renderDetail(); await api.saveTrip(state.currentTrip); return; } const add = e.target.closest('.add-member-chip'); if (add) { const name = await promptMember(''); if (!name) return; const members = getMembers(state.currentTrip); if (members.includes(name)) return; members.push(name); state.currentTrip.members = JSON.stringify(members); state.packingMember = name; render.renderDetail(); await api.saveTrip(state.currentTrip); return; } const chip = e.target.closest('.member-chip[data-member]'); if (chip) { state.packingMember = chip.dataset.member; render.renderMembers(); render.renderPacking(); } });

  if (membersContainer) membersContainer.addEventListener('dblclick', async e => { const chip = e.target.closest('.member-chip[data-member]'); if (!chip) return; const old = chip.dataset.member; const nw = await promptMember(old); if (!nw || nw === old) return; const members = getMembers(state.currentTrip); if (members.includes(nw)) return; members[members.indexOf(old)] = nw; state.currentTrip.members = JSON.stringify(members); const pk = getPacking(state.currentTrip); if (pk[old]) { pk[nw] = pk[old]; delete pk[old]; } state.currentTrip.packing = JSON.stringify(pk); if (state.packingMember === old) state.packingMember = nw; render.renderDetail(); await api.saveTrip(state.currentTrip); });

  const docList = $('doc-list'); if (docList) docList.addEventListener('click', async e => { const chk = e.target.closest('.doc-check'); if (chk) { const row = chk.closest('[data-idx]'); const idx = +row.dataset.idx; const docs = JSON.parse(state.currentTrip.documents || '[]'); docs[idx].checked = !docs[idx].checked; docs[idx].status = docs[idx].checked ? 'done' : 'draft'; state.currentTrip.documents = JSON.stringify(docs); render.renderDocs(); await api.saveTrip(state.currentTrip); return; } handleItemAction(e, 'documents'); });

  const budgetBody = $('budget-body'); if (budgetBody) budgetBody.addEventListener('click', async e => { const chk = e.target.closest('.budget-check-btn'); if (chk) { const idx = +chk.dataset.idx; const b = JSON.parse(state.currentTrip.budget || '[]'); const ns = (b[idx].status || (b[idx].paid ? 'paid' : 'unpaid')) === 'paid' ? 'unpaid' : 'paid'; b[idx].status = ns; b[idx].paid = ns === 'paid'; state.currentTrip.budget = JSON.stringify(b); render.renderBudget(); await api.saveTrip(state.currentTrip); return; } handleItemAction(e, 'budget'); });

  const packContainer = $('packing-list-container'); if (packContainer) packContainer.addEventListener('click', async e => { const chk = e.target.closest('.pack-check-btn'); if (chk) { const row = chk.closest('[data-group]'); const g = row.dataset.group; const i = +row.dataset.idx; const pk = getPacking(state.currentTrip); const md = pk[state.packingMember] || { outbound: {}, return: {} }; const sd = md[state.packingStage] || {}; if (sd[g] && sd[g][i]) { const ns = (sd[g][i].status || (sd[g][i].checked ? 'packed' : 'not_started')) === 'packed' ? 'not_started' : 'packed'; sd[g][i].status = ns; sd[g][i].checked = ns === 'packed'; md[state.packingStage] = sd; pk[state.packingMember] = md; state.currentTrip.packing = JSON.stringify(pk); render.renderPacking(); await api.saveTrip(state.currentTrip); } return; } const pe = e.target.closest('.pack-edit'); if (pe) { openPackingModal(pe.dataset.group, +pe.dataset.idx); return; } const pd = e.target.closest('.pack-dup'); if (pd) { dupPackItem(pd.dataset.group, +pd.dataset.idx); return; } const pde = e.target.closest('.pack-del'); if (pde) { delPackItem(pde.dataset.group, +pde.dataset.idx); return; } });

  const itinContent = $('itinerary-content'); if (itinContent) itinContent.addEventListener('click', async e => { const chk = e.target.closest('.itin-check-btn'); if (chk) { const row = chk.closest('[data-idx]'); const idx = +row.dataset.idx; const it = JSON.parse(state.currentTrip.itinerary || '[]'); const ns = (it[idx].status || (it[idx].checked ? 'completed' : 'planned')) === 'completed' ? 'planned' : 'completed'; it[idx].status = ns; it[idx].checked = ns === 'completed'; state.currentTrip.itinerary = JSON.stringify(it); render.renderItin(); await api.saveTrip(state.currentTrip); return; } handleItemAction(e, 'itinerary'); });

  const addDoc = $('add-doc-btn'); if (addDoc) addDoc.onclick = () => openItemModal('documents', null);
  const addBudget = $('add-budget-btn'); if (addBudget) addBudget.onclick = () => openItemModal('budget', null);
  const addPack = $('add-packing-btn'); if (addPack) addPack.onclick = () => openPackingModal('', null);
  const addItin = $('add-itin-btn'); if (addItin) addItin.onclick = () => openItemModal('itinerary', null);

  const createBtn = $('create-trip-btn'); if (createBtn) createBtn.onclick = () => openTripModal(trans('modal_title_new'), '', '');
  const modalCancel = $('modal-cancel-btn'); if (modalCancel) modalCancel.onclick = closeTripModal;

  const tripForm = $('trip-form'); if (tripForm) tripForm.addEventListener('submit', async e => {
    e.preventDefault(); const name = $('trip-name-input').value.trim(); const start = $('trip-start-input').value; const end = $('trip-end-input').value; const dates = (start && end) ? `${start} – ${end}` : (start || end || ''); const errEl = $('trip-name-error'); if (!name) { if (errEl) { errEl.textContent = trans('error_empty_name'); errEl.classList.remove('hidden'); } return; } const dup = state.trips.some(tr => { if (state.editingTripId && tr.__backendId === state.editingTripId) return false; return (tr.trip_name || '').trim().toLowerCase() === name.toLowerCase(); }); if (dup) { if (errEl) { errEl.textContent = trans('error_duplicate_name'); errEl.classList.remove('hidden'); } return; } if (errEl) errEl.classList.add('hidden'); const btn = $('modal-save-btn'); if (btn) { btn.disabled = true; btn.textContent = trans('btn_saving'); }
    if (state.editingTripId) { const trip = state.trips.find(x => x.__backendId === state.editingTripId); if (trip) { trip.trip_name = name; trip.trip_dates = dates; render.renderBookshelf(); if (state.currentTrip && state.currentTrip.__backendId === trip.__backendId) { state.currentTrip = trip; render.renderDetail(); } await api.saveTrip(trip); } } else if (state.duplicateSourceTrip) { if (state.recordCount >= 999) { if (btn) { btn.disabled = false; btn.textContent = trans('modal_btn_save'); } return; } const src = state.duplicateSourceTrip; await api.createTrip({ trip_name: name, trip_dates: dates, trip_image: src.trip_image || '', status: src.status || 'planning', created_at: new Date().toISOString(), documents: src.documents || '[]', budget: src.budget || '[]', packing: src.packing || '{}', itinerary: src.itinerary || '[]', members: src.members || JSON.stringify(['Duy', 'Vy']), previous_status: src.previous_status || '' }); } else { if (state.recordCount >= 999) { if (btn) { btn.disabled = false; btn.textContent = trans('modal_btn_save'); } return; } await api.createTrip({ trip_name: name, trip_dates: dates, trip_image: '', status: 'planning', created_at: new Date().toISOString(), documents: '[]', budget: '[]', packing: '{}', itinerary: '[]', members: JSON.stringify(['Duy', 'Vy']), previous_status: '' }); }
    if (btn) { btn.disabled = false; btn.textContent = trans('modal_btn_save'); } closeTripModal();
  });

  const itemCancel = $('item-cancel-btn'); if (itemCancel) itemCancel.onclick = () => { const over = $('item-modal-overlay'); if (over) over.classList.add('hidden'); };
  const itemSave = $('item-save-btn'); if (itemSave) itemSave.onclick = async () => {
    if (state.isSaving) return; const btn = $('item-save-btn'); const orig = btn ? btn.textContent : ''; state.isSaving = true; if (btn) { btn.disabled = true; btn.textContent = trans('btn_saving'); }
    try { const form = $('item-form'); const fd = new FormData(form); const v = {}; fd.forEach((val, k) => v[k] = val); const { tabType, idx, group } = state.itemModal; const isNew = idx === null || idx === undefined; const trip = state.currentTrip;
      if (tabType === 'documents') { const arr = getDocs(trip); const sv = v.status || 'draft'; const obj = { id: isNew ? genId() : (arr[idx]?.id || genId()), name: v.name || '', pic: v.pic || '', cost: v.cost || '', start_date: v.start_date || '', end_date: v.end_date || '', notes: v.notes || '', status: sv, checked: sv === 'done' }; if (isNew) arr.push(obj); else arr[idx] = obj; trip.documents = JSON.stringify(arr); }
      else if (tabType === 'budget') { const arr = getBudget(trip); const sv = v.status || 'unpaid'; const obj = { id: isNew ? genId() : (arr[idx]?.id || genId()), name: v.name || '', cost: String(v.cost || '').replace(/[^\d.]/g, ''), currency: v.currency || 'VND', status: sv, paid: sv === 'paid', note: v.note || '', link: v.link || '' }; if (isNew) arr.push(obj); else arr[idx] = obj; trip.budget = JSON.stringify(arr); }
      else if (tabType === 'itinerary') { const arr = getItin(trip); const obj = { id: isNew ? genId() : (arr[idx]?.id || genId()), date: v.date || '', time: fmtTime24(v.time || ''), title: v.title || '', location: v.location || '', notes: v.notes || '', status: v.status || 'planned', checked: v.status === 'completed' }; if (isNew) arr.push(obj); else arr[idx] = obj; trip.itinerary = JSON.stringify(arr); }
      else if (tabType === 'packing') { const pk = getPacking(trip); const md = pk[state.packingMember] || { outbound: {}, return: {} }; const sd = md[state.packingStage] || {}; const cat = v.category || 'Other'; const sv = v.status || 'not_started'; const obj = { id: isNew ? genId() : ((sd[group] && sd[group][idx])?.id || genId()), item: v.item || '', note: v.note || '', status: sv, checked: sv === 'packed' }; if (isNew) { if (!sd[cat]) sd[cat] = []; sd[cat].push(obj); } else { if (group !== cat) { if (sd[group]) sd[group].splice(idx, 1); if (sd[group] && !sd[group].length) delete sd[group]; if (!sd[cat]) sd[cat] = []; sd[cat].push(obj); } else sd[group][idx] = obj; } md[state.packingStage] = sd; pk[state.packingMember] = md; trip.packing = JSON.stringify(pk); }
      const overlay = $('item-modal-overlay'); if (overlay) overlay.classList.add('hidden'); render.renderDetail(); await api.saveTrip(trip);
    } finally { if (btn) { btn.disabled = false; btn.textContent = orig; } state.isSaving = false; }
  };

  const contextMenu = $('context-menu'); if (contextMenu) contextMenu.addEventListener('click', async e => { const btn = e.target.closest('[data-action]'); if (!btn || !state.contextTripId) return; const action = btn.dataset.action; const trip = state.trips.find(x => x.__backendId === state.contextTripId); if (!trip) return; contextMenu.classList.add('hidden'); if (action === 'rename') { state.editingTripId = state.contextTripId; state.duplicateSourceTrip = null; openTripModal(trans('modal_title_rename'), trip.trip_name, trip.trip_dates); state.editingTripId = state.contextTripId; } else if (action === 'duplicate') { state.duplicateSourceTrip = trip; state.editingTripId = null; const sfx = state.lang === 'vi' ? ' (bản sao)' : ' (copy)'; openTripModal(trans('modal_title_duplicate'), (trip.trip_name || '') + sfx, trip.trip_dates); state.duplicateSourceTrip = trip; } else if (action === 'archive') { if (trip.status === 'archived') { trip.status = trip.previous_status || 'planning'; trip.previous_status = ''; } else { trip.previous_status = trip.status || 'planning'; trip.status = 'archived'; } await api.saveTrip(trip); render.renderBookshelf(render.renderTripCard, render.renderArchivedCard); if (state.currentTrip && state.currentTrip.__backendId === trip.__backendId) { state.currentTrip = trip; render.renderDetail(); } } else if (action === 'delete') { state.trips = state.trips.filter(x => x.__backendId !== state.contextTripId); render.renderBookshelf(render.renderTripCard, render.renderArchivedCard); await api.deleteTrip(trip); } });

  document.addEventListener('click', e => { if (!e.target.closest('#context-menu') && !e.target.closest('.menu-btn')) { const ctx = $('context-menu'); if (ctx) ctx.classList.add('hidden'); } });
  document.addEventListener('keydown', e => { if (e.key === 'Escape') { const ctx = $('context-menu'); if (ctx) ctx.classList.add('hidden'); const overlay = $('modal-overlay'); if (overlay && !overlay.classList.contains('hidden')) closeTripModal(); const itemOverlay = $('item-modal-overlay'); if (itemOverlay && !itemOverlay.classList.contains('hidden')) itemOverlay.classList.add('hidden'); } });
}

export async function boot() {
  // splash
  const splash = $('splash-screen'); const progress = $('splash-progress'), plane = $('splash-plane'), city = $('splash-city'); if (plane) setTimeout(() => { plane.style.transition = 'all 1.8s cubic-bezier(.25,1,.5,1)'; plane.style.opacity = '1'; plane.style.transform = 'translate(110px,-10px) rotate(-5deg) scale(1.1)'; }, 200); if (city) setTimeout(() => { city.style.transition = 'all 1.2s cubic-bezier(.34,1.56,.64,1)'; city.style.opacity = '1'; city.style.transform = 'translateY(0)'; }, 900); if (plane) setTimeout(() => { plane.style.transition = 'all 1.5s cubic-bezier(.55,0,1,1)'; plane.style.transform = 'translate(360px,-40px) rotate(-15deg) scale(.8)'; plane.style.opacity = '0'; }, 2000);
  const dur = 3000, start = performance.now(); (function tick(now) { const done = false; const p = Math.min((now - start) / dur * 100, 100); if (progress) progress.style.width = p + '%'; if (p < 100) requestAnimationFrame(tick); else if (splash) { splash.style.transition = 'opacity .7s ease'; splash.style.opacity = '0'; splash.style.pointerEvents = 'none'; setTimeout(() => splash.remove(), 750); } })(start);

  // build selects
  const statusFilter = $('status-filter'); if (statusFilter) statusFilter.innerHTML = [['all', 'filter_all'], ['planning', 'filter_planning'], ['active', 'filter_active'], ['completed', 'filter_completed'], ['archived', 'filter_archived']].map(([v, k]) => `<option value="${v}">${trans(k)}</option>`).join('');
  const sortSelect = $('sort-select'); if (sortSelect) sortSelect.innerHTML = [['newest', 'sort_newest'], ['oldest', 'sort_oldest'], ['name', 'sort_name']].map(([v, k]) => `<option value="${v}">${trans(k)}</option>`).join('');

  render.renderTabBar(); bindTabBar(); bindEvents();

  // set language UI buttons
  const langVi = $('lang-vi'); const langEn = $('lang-en'); if (langVi) langVi.className = `text-xs font-semibold px-2 py-1 rounded-full transition-all ${state.lang === 'vi' ? 'bg-emerald-600 text-white' : 'text-gray-500 hover:text-emerald-600'}`; if (langEn) langEn.className = `text-xs font-semibold px-2 py-1 rounded-full transition-all ${state.lang === 'en' ? 'bg-emerald-600 text-white' : 'text-gray-500 hover:text-emerald-600'}`;

  // i18n text population (call once)
  document.querySelectorAll('[data-i18n]').forEach(el => { const k = el.getAttribute('data-i18n'); const dict = window.__voyageI18N && window.__voyageI18N[state.lang]; if (dict && dict[k]) el.textContent = dict[k]; });
  const searchInput = $('search-input'); if (searchInput) searchInput.placeholder = (window.__voyageI18N && window.__voyageI18N[state.lang] && window.__voyageI18N[state.lang]['search_placeholder']) || 'Search...';

  // Initialize dataSdk
  const r = await api.initDataSdk({ onDataChanged(data) { state.trips = data; state.recordCount = data.length; if (state.lastUpdate.id && (Date.now() - state.lastUpdate.ts < 4000)) { const i = state.trips.findIndex(x => x.__backendId === state.lastUpdate.id); if (i !== -1) state.trips[i] = { ...state.trips[i], ...state.lastUpdate.data }; } render.renderBookshelf(render.renderTripCard, render.renderArchivedCard); if (state.currentTrip) { const u = state.trips.find(x => x.__backendId === state.currentTrip.__backendId); if (u) { state.currentTrip = u; render.renderDetail(); } } }
  });
  if (!r.isOk) { const shelf = $('bookshelf'); if (shelf) shelf.innerHTML = '<p class="text-center text-red-400 text-sm py-4">Failed to load data.</p>'; }
  if (window.lucide) window.lucide.createIcons();
}
